### ISSUE TITLE
File not found for template.php. node.tpl.php etc.

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/api.backdropcms.org#8]
The API site seems to automatically turn certain entries into links, such as function names and templates and constants etc, which link to documentation about that function.
But certain of these links when clicked say file not found (template.php., node.tpl.php)
Plus, if you paste these rogue entries (such as template.php) in the autocomplete search field on the API site (dont type it in and select, just paste the whole phrase), you get an AJAX popup error.

**Comment by quicksketch** [comment]
Thanks @docwilmot. Seems like our new Backdrop-based site inherited this error from the D7 API module as well. I'll take a look at fixing it in the API project.

**Comment by quicksketch** [comment]
This was caused by the configuration of our nginx server. Any non-root file that ended in .php was being given an access denied error. Since the autocomplete uses the text the user types in, ending a search in `.php` resulted in the autocomplete getting an access denied. I've fixed the configuration in nginx so autocomplete is working again.
