### ISSUE TITLE
Fix the code in hook_admin_bar_output_build

### ISSUE THREAD

**Issue by alanmels** [backdrop-ops/api.backdropcms.org#99]
Example on https://api.backdropcms.org/api/backdrop/core%21modules%21admin_bar%21admin_bar.api.php/function/hook_admin_bar_output_build/1 never works unless the following line:

```
$content['menu']['myitem'] = array(
```

is changed to

```
$content['menu']['menu']['myitem'] = array(
```

Please update the documentation page.

**Comment by BWPanda** [comment]
Thanks for reporting this @alanmels. Since Admin Bar is part of Backdrop core, you'll need to file an issue in the [core queue](https://github.com/backdrop/backdrop-issues/issues) and the PR against [core itself](https://github.com/backdrop/backdrop/pulls).

If/when that's merged, the API site will pull from core and update automatically.
